name: OPTIMISEGLOBALPARTNERS.COM
favicon: null
layout_spectrum: 0.73706
typography_spectrum: 0.58848
title: OPTIMISE GLOBAL PARTNERS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bac7d1'
    - '#0b1856'
    - '#475661'
    - '#e5e5e5'
    - '#8991ac'
  brandStrength: 0.125
  lightness: 0.2537779682315886
  saturation: 0.23467940581031144
  rhythmicContrast: 0.75
purpose: []
