name: OPTIMISEGLOBALPARTNERS.COM
favicon: null
layout_spectrum: 0.75208
typography_spectrum: 0.69032
title: OPTIMISE GLOBAL PARTNERS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bac7d1'
    - '#0b1856'
    - '#475661'
    - '#e5e5e5'
    - '#8991ac'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
