name: OPTIMISEGLOBALPARTNERS.COM
favicon: null
layout_spectrum: 0.91402
typography_spectrum: 0.69366
title: OPTIMISE GLOBAL PARTNERS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe9c7'
    - '#2d182b'
    - '#dcaf8e'
    - '#707ea1'
    - '#475481'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
